In [1]:
import numpy as np
import pandas as pd

In [2]:
dx = pd.read_csv('/Users/lisonghe/Library/CloudStorage/OneDrive-JohnsHopkins/Semester 2/602 Research and Design in Data Mining/files/DIAGNOSIS.csv')

In [3]:
dx.head()

,Unnamed: 0,STUDY_DX_ID,STUDY_ENC_ID,STUDY_PAT_ID,DX_START_DATETIME,DX_END_DATETIME,DX_SOURCE_TYPE,DX_ENC_TYPE,DX_CODE_TYPE,DX_CODE,DX_NAME,DX_ALT_CODE,CLASS_OF_PROBLEM,CHRONIC_YN,PROV_ID
0,0,10001,55902925,13210,2018-09-07 00:00:00,2018-09-07 00:00:00,Primary Encounter Dx,Encounter Dx,ICD10,R56.9,Seizure,780.39,NaN,NaN,3001267.0
1,1,10017,55772269,12547,2014-11-01 00:00:00,2014-11-01 00:00:00,Secondary Encounter Dx,Encounter Dx,ICD9,790.7,Positive blood culture,R78.81,NaN,NaN,3001267.0
2,2,10018,55772269,12547,2014-11-01 19:58:00,2014-11-01 23:08:00,Admit Dx,Admit Dx,ICD9,796.4,Other abnormal clinical finding,R68.89,NaN,NaN,3001267.0
3,3,10019,55772269,12547,2014-11-01 19:58:00,2014-11-01 23:08:00,Final Dx,Final Dx,ICD9,796.4,Other abnormal clinical finding,R68.89,NaN,NaN,3001267.0
4,4,10020,56359534,7138,2019-05-18 00:00:00,2019-05-18 00:00:00,Secondary Encounter Dx,Encounter Dx,ICD10,J06.9,Viral URI,465.9,NaN,NaN,3001267.0

In [4]:
apnea_rows = dx[dx['DX_NAME'].str.contains('apnea', case=False, na=False)]
apnea_count = apnea_rows.shape[0]
apnea_count

24860

In [5]:
distinct_apnea_rows = apnea_rows.drop_duplicates(subset=['STUDY_PAT_ID'])

In [6]:
merged = pd.read_csv('/Users/lisonghe/Library/CloudStorage/OneDrive-JohnsHopkins/Semester 2/602 Research and Design in Data Mining/merged.csv')
merged1 = merged.merge(distinct_apnea_rows[['STUDY_PAT_ID', 'DX_NAME']], on='STUDY_PAT_ID', how='left')
merged1

,STUDY_PAT_ID,SLEEP_STUDY_ID,AGE,SLEEP_DURATION,HIGH BP,LOW BP,BMI,GENDER,RACE,AHI,APNEA_NAME,HAVE_APNEA?,DX_NAME
0,1,4789,9.145205,9:35:32,105.0,65.0,17.37,M,White,0.00,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
1,7,12595,2.123288,11:22:32,120.0,54.0,15.63,F,White,0.54,Apnea,Yes,Apnea
2,10,22339,13.101370,11:14:13,127.0,70.0,31.75,F,Black or African American,3.47,"Obstructive sleep apnea hypopnea, mild",Yes,"Obstructive sleep apnea hypopnea, mild"
3,16,24241,12.076712,10:03:36,102.0,65.0,16.17,M,White,0.00,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
4,22,23233,4.739726,11:15:36,86.0,52.0,18.04,M,Black or African American,0.28,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3979,20812,24841,5.238356,11:45:15,NaN,NaN,15.22,F,White,0.49,Apnea,Yes,Apnea
3980,20821,18340,15.679452,9:38:16,109.0,85.0,20.56,F,White,0.00,NaN,No,NaN
3981,20824,1357,12.389041,11:34:21,107.0,59.0,23.89,M,White,0.00,NaN,No,NaN
3982,20827,7042,13.378082,9:32:59,115.0,79.0,37.35,F,Multiple race,0.13,OSA (obstructive sleep apnea),Yes,OSA (obstructive sleep apnea)
3983,20830,14089,24.030137,12:05:09,109.0,65.0,19.31,M,White,0.39,Obstructive sleep apnea (adult) (pediatric),Yes,Obstructive sleep apnea (adult) (pediatric)

In [7]:
merged1['HAVE_APNEA?'] = np.where(merged1['DX_NAME'].isna(), 'No', 'Yes')
merged1.rename(columns={'DX_NAME': 'APNEA_NAME'}, inplace=True)
merged1.head(10)

,STUDY_PAT_ID,SLEEP_STUDY_ID,AGE,SLEEP_DURATION,HIGH BP,LOW BP,BMI,GENDER,RACE,AHI,APNEA_NAME,HAVE_APNEA?,APNEA_NAME
0,1,4789,9.145205,9:35:32,105.0,65.0,17.37,M,White,0.00,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
1,7,12595,2.123288,11:22:32,120.0,54.0,15.63,F,White,0.54,Apnea,Yes,Apnea
2,10,22339,13.101370,11:14:13,127.0,70.0,31.75,F,Black or African American,3.47,"Obstructive sleep apnea hypopnea, mild",Yes,"Obstructive sleep apnea hypopnea, mild"
3,16,24241,12.076712,10:03:36,102.0,65.0,16.17,M,White,0.00,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
4,22,23233,4.739726,11:15:36,86.0,52.0,18.04,M,Black or African American,0.28,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
5,25,18085,17.926027,12:52:22,146.0,96.0,46.87,M,White,10.47,Obstructive sleep apnea syndrome,Yes,Obstructive sleep apnea syndrome
6,25,10579,18.906849,10:22:20,124.0,79.0,48.45,M,White,1.13,Obstructive sleep apnea syndrome,Yes,Obstructive sleep apnea syndrome
7,28,15280,6.169863,10:34:00,NaN,NaN,16.10,M,White,0.13,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
8,31,4429,3.139726,11:09:32,88.0,61.0,16.22,F,Black or African American,0.12,"Sleep apnea, unspecified",Yes,"Sleep apnea, unspecified"
9,37,14779,9.605479,9:53:30,141.0,101.0,38.76,M,White,0.68,"Sleep apnea, unspecified type",Yes,"Sleep apnea, unspecified type"

In [8]:
merged1.to_csv('merged.csv', index=False)

In [9]:
condition1 = (merged1['AHI'] != 0) 
condition2 = (merged1['HAVE_APNEA?'] == 'Yes')  
AHI_accuracy = (condition1 & condition2).sum() / merged1.shape[0]
AHI_accuracy

0.6762048192771084

In [11]:
merged1[merged1['AHI'] == 0][['AHI', 'HAVE_APNEA?']].head(30)

     AHI HAVE_APNEA?
0    0.0         Yes
3    0.0         Yes
22   0.0         Yes
24   0.0         Yes
26   0.0         Yes
42   0.0          No
43   0.0         Yes
44   0.0         Yes
54   0.0          No
60   0.0         Yes
63   0.0         Yes
66   0.0         Yes
72   0.0          No
79   0.0          No
96   0.0         Yes
101  0.0         Yes
110  0.0         Yes
114  0.0         Yes
122  0.0          No
124  0.0         Yes
134  0.0          No
141  0.0         Yes
143  0.0         Yes
144  0.0         Yes
148  0.0          No
149  0.0          No
151  0.0          No
152  0.0         Yes
156  0.0          No
161  0.0         Yes

In [4]:
import pandas as pd
import numpy as np
data = pd.read_csv('/Users/lisonghe/Library/CloudStorage/OneDrive-JohnsHopkins/Semester 2/602 Research and Design in Data Mining/merged.csv')
data['HAVE_APNEA?'] = np.where(data['APNEA_NAME'].isna(), 0, 1)
data.head()
data.to_csv("merged.csv", index = False)